import './globals.sass';

import type { Metadata } from 'next';
import { ThemeProvider } from '@/lib/modules/ThemeModule';
import { NotificationsProvider } from '@/lib/modules/NotificationsModule';
import { StoreProvider } from '@/lib/store/StoreProvider';
import { Roboto } from 'next/font/google';
import { Auth } from '@/lib/auth/Auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-roboto',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <StoreProvider>
          <ThemeProvider>
            <Auth>
              <NotificationsProvider
                anchorOrigin={{
                  vertical: 'bottom', // 'top' | 'bottom'
                  horizontal: 'right', // 'left' | 'center' | 'right'
                }}
                maxSnack={3}
              >
                {children}
              </NotificationsProvider>
            </Auth>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
